### ISSUE TITLE
Missing Google logo

### ISSUE THREAD

**Issue by jidanni** [grst/geos#32]
On http://geos-web.herokuapp.com/ for legal reasons, shouldn't there be a Google logo in the corner of the map?

**Comment by grst** [comment]
Hi @jidanni, 

thanks for pointing that out! Do you have any reference to documentation from google that states this requirement? 

Best regards, 
Gregor

**Comment by jidanni** [comment]
https://about.google/brand-resource-center/products-and-services/geo-guidelines/#required-attribution

**Comment by jidanni** [comment]
https://developers.google.com/maps/documentation/gaming/attribution etc.

**Comment by jidanni** [comment]
https://developers.google.com/maps/documentation/places/web-service/policies etc.

**Comment by grst** [comment]
Thanks, I'll address that soon!

**Comment by jidanni** [comment]
All I know is
https://developers.google.com/maps/documentation/javascript/examples/map-simple
has a handy Google link in the left lower corner that takes one to Google Maps for that location.
And also in the right lower corner. a maps data copyright...
And it is all automatically put there.

**Comment by grst** [comment]
I found out that strictly speaking, even with the attribution notice, it is not allowed to access google maps by tile URL (instead of using the official API). 

I, therefore, deemed it safest to remove the google maps entirely from the public web app. Anyone is free to run `geos` locally at own risk with any map they like. 

Thanks again for bringing my attention to this!
